project:
  type: website
  preview:
    port: 5000
    host: 0.0.0.0
  render:
    - "*.qmd"


website: 
  page-navigation: true
  site-url: "https://thomasfaria.github.io/retex-innovation-insee" 
  repo-url: "https://github.com/ThomasFaria/retex-innovation-insee"
  # repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  
  sidebar:
    style: "docked"
    contents:
      - text: "Introduction"
        href: src/introduction/index.qmd
      - text: "Principes"
        href: src/principles/index.qmd
      - text: "Implémentations"
        href: src/implementation/index.qmd
      - text: "MLOps"
        href: src/mlops/index.qmd
      - text: "Discussion"
        href: src/discussion/index.qmd

    background: "#D9E3E4"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: file-pdf-fill
        href: src/index.pdf
        text: "PDF"

format:
  html:
    theme: cosmo
    css: styles/styles.css
    toc: true
    code-annotations: hover
    code-link: true

bibliography: src/references.bib 
