name: Publish website and pdf

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Quarto
    - name: Set up quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # Step 3: Compile FR document
    - name: Render FR version
      uses: quarto-dev/quarto-actions/render@v2
      env:
        QUARTO_PROFILE: fr

    # Step 4: Compile EN document
    - name: Render EN version
      uses: quarto-dev/quarto-actions/render@v2
      env:
        QUARTO_PROFILE: en

    # Step 3: Compile document
    - name: Publish to GitHub Pages
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        render: false
        target: gh-pages
